### ISSUE TITLE
Alguien me ayuda a traducir? 

### ISSUE THREAD

**Issue by mora145** [Ludeon/RimWorld-Spanish#22]
Estoy con `RimWorld-Spanish/Backstories/Backstories.xml`. La traducción del archivo tiene 2500 lineas. Voy por la 1500. Alguien se anota para ayudarme? Estoy traduciendo mediante un archivo exel, previa extracción de lo que se debe de traducir.

**Comment by Emsaic** [comment]
Te ayudo, ¿Por cual vas ahora o cuales te serviría que haga?

**Comment by mora145** [comment]
@Emsaic porfavor enviame un correo donde hacerte llegar los textos a traducir.

**Comment by mora145** [comment]
[Origen.xlsx](https://github.com/Ludeon/RimWorld-Spanish/files/908274/Origen.xlsx)

@Emsaic

**Comment by loneplayer18** [comment]
Una pregunta. Yo solo tendria que editar lineas de texto y despues
enviarlas a tu correo??

**Comment by mora145** [comment]
@loneplayer18 Crea un archivo nuevo en excel (Los puedes llamar "Destino"), y vas traduciendo en ese, lo que subí ("Origen"). Yo uso los dos archivos encogiendo las ventanas y trabajando los dos a la vez. 

Y claro, una vez que lo tengas traducido me lo envias por esta vía. Asi lo añado a una memoria de traduccion que tengo en el Software Tradado's; él lo añade automaticamente al archivo original del juego.

**Comment by mora145** [comment]
@loneplayer18 Esta es la forma en la que yo trabajo los dos archivos a la vez, el de origen y el de la traducción. 
![excel](https://cloud.githubusercontent.com/assets/25883820/24872356/2b598cf2-1deb-11e7-994e-12729f70948e.jpg)

**Comment by mora145** [comment]
@loneplayer18 Por favor, notificarme si puede terminar esas lineas para mañana.

**Comment by loneplayer18** [comment]
Cuantas son??

**Comment by loneplayer18** [comment]
CUantas y cuales?

**Comment by mora145** [comment]
@loneplayer18 Estan arriba. "Origen" son 800, pero si puedes llegar a las 500 estaria bien.

**Comment by mora145** [comment]
Ante ayer logre hace 1500, pero estoy trabajando y no me ha dado tiempo de seguir.

**Comment by loneplayer18** [comment]
Vale

**Comment by loneplayer18** [comment]
Im sorry, my pc has blowed up and i cant work. Maybe I can help you other
day with other thing.

**Comment by loneplayer18** [comment]
Lo siento mi ordenador se a roto y no puedo trabajar en esto. Tal vez otro
dia pueda ayudarte.

**Comment by mora145** [comment]
scared? XD

**Comment by amatiasq** [comment]
@mora145 Perdona pero me puedes explicar porqué usar un excel? eso es lo que usábamos antes de que existiera Git, que es un sistema que permite a un grupo de gente trabajar sobre un mismo código sin necesidad de mandar archivos por correo. Además así queda registrado quién aportó qué.

En todo caso no me parece apropiado pedir resultados "para mañana". No creo que debamos presionar a nadie, cada uno aportará lo que pueda. Hacemos esto por hobby, si nos ponemos fechas los unos a los otros la única diferencia entre esto y un trabajo sería que en el trabajo te pagan.

**Comment by mora145** [comment]
@amatiasq Uso excel porque es mas fácil manejar las traducciones, ademas de ser mas rápido, solo ir linea por linea. ¿Por qué lo uso? Porque con el software Trados, puedo extraer justo lo que se va a traducir sin necesidad ir buscándolo por todo el código, al igual que insertarlo a la hora de haberlo terminado. ¿Por qué pido a la brevedad posible? Porque la idea sería subir todo el archivo terminado de una vez; yo por un lado voy con una parte, y hoy o mañana ya debería estar lista, para entre los dos subir todo el archivo. Pensaba darle la autoría de la traducción a los dos (Junto con quien me ayudara), pero a la final todos retrocedieron, así que me lancé solo con las 2500 lineas. Espero terminarlas pronto.

**Comment by amatiasq** [comment]
Me he explicado mal, la pregunta no era porqué usar Excel, sino porqué hacer que los demás lo usen. Igualmente el tema no es poner fecha para que te manden las cosas sino porqué pedir que te las manden a ti en lugar de publicarlas ellos mismos, si cada uno publica lo suyo no hay fechas ni presiones.

**Comment by mora145** [comment]
Entiendo. Bueno es que tengo las 2500 lineas pasadas a un archivo Excel, por la comodidad preferí enviarlas por esa vía (Solo copiar y pegar la parte que me faltaba) ¿que si es una regla usarlo? Para nada, pero sería un poco extraño copiar linea por linea de vuelta al código, manualmente; teniendo un programa que lo haga automático. Fíjate que dije que esa era la forma en la que "yo lo hacía" por lo rápido y por lo organizado, al ser muchas lineas de traducción, mas no lo impuse como una norma. Y como es un solo archivo, sería bueno que todo fuera en un solo sentir. 

Lo de las fechas ya te lo expliqué. Un solo archivo, un solo trabajo, un solo proceso al añadirlo al codigo; una sola memoria de traducción. 

A la final entiendo tu disgusto. Subiré el archivo mediante otra vía. Saludos.
