### ISSUE TITLE
Hay alguien trabajando?

### ISSUE THREAD

**Issue by Arapiles92** [Ludeon/RimWorld-Spanish#24]
Hola a todos me he ofrecido para ayudar con la traducción del juego. No se si todavía queda alguien, veo que las traducciones son de hace unos meses. Si no contesta nadie me podre a repasar-lo todo si no pues el que este mas al corriente que me informe y me pongo a currar cuanto antes.

**Comment by Gabrielt0** [comment]
Hola yo recuerdo que me suscribi para ver como hacian las traduccion pero ya salio una nueva actualizacion de rimworld y parece que estan inactivos, si yo supiera como traducirlos lo haria :(

**Comment by mora145** [comment]
Sigo activo, aunque estoy ahora mas con las traducciones del HardCore-SK. Si vi en los videos de la A17 que hicieron cambios al parecer, en la barra de abajo, y por lo visto la traducción no reconoce el defName. Vere si consigo donde está fallando con respecto a esto. 

Con respecto a lo demas, sería nada mas verificación y corrección.
