### ISSUE TITLE
Facciones B18

### ISSUE THREAD

**Issue by snowy86** [Ludeon/RimWorld-Spanish#33]
Con la nueva beta18, los poblados y outpost no tienen nombre, y se muestra la frase "Could not resolve any root"

In Beta 18, villages and outpost have no name, instead "Could not resolve any root" appears.

**Comment by snowy86** [comment]
Mecatxis encontró el problema, en el foro de Ludeon puso esto:
"El fallo fué por un error de formato en el fichero DefInjected/RulePackDef/RulePacks_NameMakers_Factions.xml. Revisalo (o directamente borralo, si no te importa que salgan en inglés)"

**Comment by mora145** [comment]
Revisaré si ya fue solucionado.

**Comment by mora145** [comment]
Saludos @snowy86 hice varias modificaciones. Por favor avísame si continua la falla.

**Comment by snowy86** [comment]
Perdona @mora145, estuve tiempo sin PC. Acabo de instalarlo hoy y sigue el fallo.

**Comment by mora145** [comment]
Saludos @snowy86 prueba borrando el archivo RimWorld/Languages/Spanish/DefInjected/RulePackDef/RulePacks_NameMakers_Factions.xml

**Comment by snowy86** [comment]
@mora145 , funciona, aunque la única pega sería que están en inglés esos nombres. Bueno, siempre es mejor que el "Could not resolve any root", jejej. Gracias.
