### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 764380732331** [Ludeon/RimWorld-Spanish#37]
Por alguna singularidad de esta traducción el generador de semillas no funciona, bloqueando la creación de un nuevo mundo.

`could not resolve any root: r_seed firstrulepack: seedgenerator`
El mensaje de error en la interfaz, pegaría el texto de la consola al intentar crearlo pero es interminable y de todos modos muy fácil de reproducir.

¡Gracias por vuestro tiempo y trabajo!

**Comment by Ghrull** [comment]
Borra la carpeta "RulePackDef", (rimworld\mods\core\languages\spanish\DefInjected\RulePackDef) los nombres te saldrán en ingles y no te debería dar errores, la traducción española no se actualizaba desde la alpha 16, yo empece a traducir hace como 3 semanas y aun me queda bastante porque estoy traduciendo el juego yo solo, lo antiguos traductores llevan años ausentes.

**Comment by mora145** [comment]
@Ghrull Estas traduciendo las Rules? Dime, para darte una mano.

**Comment by Ghrull** [comment]
@mora145 ahora mismo mientras encuentro una solución para la carpeta Rulepackdef estoy traduciendo la carpeta Thingdef. Ya la tengo casi terminada, en cuanto la suba, si queréis podéis echarle un vistazo, adaptarla al español latino si fuese necesario y subirla a github ya que cambiaron bastantes cosas y os ahorraría mucho trabajo.

**Comment by mora145** [comment]
@Ghrull Ya veo el problema. Estoy conversardo por el canal a ver que me dicen sobre las nuevas traducciones. Ok, las espero, cuando las subas las reviso y las paso al latino. Gracias!

**Comment by 764380732331** [comment]
@Ghrull ¡Muchas gracias! Sin "RulePackDef" funciona correctamente, mencionar también que con el parche de @mora145 persiste el error, por otro lado ni tengo claro si en su estado actual era lo esperado.

Lamentablemente mi ingles está muy verde y de programación mejor ni hablemos, pero necesitáis ayuda para buscar errores o cadenas sin traducir podéis contar conmigo :)

**Comment by 764380732331** [comment]
@Ghrull Puede que sea de interés, especialmente el apartado 2) dedicado a "RulePackDef".

[https://ludeon.com/forums/index.php?&topic=41942.0](url)

**Comment by mora145** [comment]
Los demas han adopatado las que pasé (Claro, cambiando el idioma) Fueron generadas con expresiones regulares en notepad++. Yo no he tenido la oportunidad de probarlas, pero segun, no funcionan.

**Comment by mora145** [comment]
@Ghrull @764380732331 Segun leí fue @isonil quien ejecutó el script para transformar las RulePackDef.

**Comment by mora145** [comment]
Solo debemos traducir y ya.

**Comment by mora145** [comment]
@isonil We have a persistent problem since past versions in which the names of caravans, visitors and some factions come out as "could not resolve". Do you have information to solve it?

**Comment by isonil** [comment]
@mora145 I'm not sure, maybe it's because some keywords are missing. There's a debug setting which can help debug this. It's called "Log grammar resolution". This output would help me figure out what's causing this.

The new full-list syntax (with \<li> nodes) shouldn't cause such issues.

![log grammar](https://user-images.githubusercontent.com/8492408/41821157-bd5bc0ce-77dc-11e8-88bf-e018e0c8d031.png)

**Comment by mora145** [comment]
@isonil Thx!  I need review this. I will comment you
