### ISSUE TITLE
Para ayudar

### ISSUE THREAD

**Issue by colo13verdadeo** [Ludeon/RimWorld-Spanish#41]
Buenas me presento:
Soy colo13, vengo a ayudar a traducir después de varios años de ausencia. Me gustaria saber en que hace falta asi ayudo?

Tengo poca experiencia programando con java y unity,  Mi ingles es medio pero sirve (: :+1: 

Ahora sere mas activo;

Para contactarme: 
  Discord: colo13#2839
  Skype (no lo uso ya) colo13verdadeo
  Facebook: /joaquinmvmv
  Whatsapp: (pedir por privado)

**Comment by 764380732331** [comment]
@colo13verdadeo ¡Saludos! Hay cambios recientes en sintaxis y generación de informes de errores en traducciones que quizás no conozcas, te animo a echar un vistazo a [este](https://ludeon.com/forums/index.php?&topic=41942.0) enlace.

Hasta donde yo se por el contenido de Github (siento no poder aportar nada más) @mora145 se está haciendo cargo de "RulePackDef" y puede que le venga bien que le echen una mano, @Ghrull mencionó que estaba con "Thingdef" pero de eso hace ya 3 semanas. Tristemente ahi termina la lista de traductores actuales :s

**Comment by colo13verdadeo** [comment]
"Argument count mismatches: warnings when the number of arguments in English is different (e.g. English text uses {0}, {1} while the translation uses only {0}). These are not necessarily errors, sometimes it's ok."

Quiso decir en otras palabras que en la traduccion a los demas idiomas solo se usa el "{0}"?
Y en el ingles solo {0} y {1}?

**Comment by colo13verdadeo** [comment]
Podria hablarte por otro medio?

**Comment by mora145** [comment]
Hola @colo13verdadeo Bienvenido. Saludos tambien a @764380732331 si he estado traduciendo las rules y arreglando los errores al respecto, pero me he concentrado mas en la traduccion Spanish Latin. 

Si ustedes estan de acuerdo, puedo pasar los avances que he hecho a este reposorio e ir luego adaptandolos al Castellano. Ya solucioné muchos de los errores de "Could Not Resolve" que aparecían. Sería bueno que revisen el reposorio Latino, allí hemos estado dando los ajustes a la 1.0.

**Comment by colo13verdadeo** [comment]
Podria contactar con usted por otro medio?
@mora145 
@764380732331
