### ISSUE TITLE
Adaptación y revisión de textos

### ISSUE THREAD

**Issue by Xeros08** [Ludeon/RimWorld-Spanish#47]
He utilizado los archivos de la traducción latinoamericana como base para continuar con la traducción para la 1.1, ya que la traducción fue abandonado en 2018 por los traductores originales (Español de España) y ha sido retomada en 2020 por mí. (De momento).

**Comment by Maverik2** [comment]
Gracias por tu trabajo, una peticion que te haria es que revises muchas palabras latinas que ahora han cambiado, llevabamos años acostumbrados a leerlas en español y ahora choca un poco ver que han cambiado algunas cosas. Como minimo dejar eso como estaba. Una vez mas gracias por tu esfuerzo.

**Comment by Xeros08** [comment]
Sin problemas, aunque, de hecho es lo que estoy haciendo. Me estoy centrando en las primeras cosas que se ven, como los trasfondos, menús y diálogos.

Eventualmente llegaré a todo, ya que el juego es bastante amplio.

**Comment by Xeros08** [comment]
P.D: Rimworld es un juego muy grande y he decidido ahorrarme trabajo de esta forma ya que estoy solo.

Igualmente, las traducciones latinas eran de mayor calidad, así que no creo que sea mucho problema, ya que en un mes o así tendré revisadas todos los trasfondos, que es lo que más tiempo consume.

**Comment by Andres6936** [comment]
Buen día, soy actual traductor de la sección latinoamericana {**Spanish Latin**}, mi pregunta es: 

¿Qué tanto difieren las palabras y términos _Latinoamericanos_ con respecto a sus contrapartes _Españolas_?.

Estoy interesado en unir ambas secciones en una sola {_Wikipedia es un gran ejemplo de unificar varios dialectos en una sola sección_}, sin embargo, no quiero incomodar a lectores latinoamericanos ni tampoco a lectores españoles con términos  y palabras que molesten.

¿Existe disposición para realizar esta unión?

**Comment by Xeros08** [comment]
@Andress6936 por mi parte no, opino que es mejor que exista una diferenciación en las traducciones de los juegos en lo que al Español respecta, ya que; 
1• Por algo existen los términos diferenciadores "Español Castellano" y "Español Latino".

2• Hace que sea mejor para el lector, posible jugador y los traductores. Unificar las traducciones implica, muchas veces, usar lenguaje más culto y común a ambos dialectos. Además, requiere de más tiempo y recursos de los traductores.

3• Aunque hagamos esto de gratis, por amor al arte, ya es mucho trabajo de normal, como para querer hacer de cero, OTRA VEZ, todo , y perder lo que ya tenemos hecho.

4• Lo prefiero así ¯\_(ツ)_/¯. Que luego hay demasiados dolores de cabeza, y ya hay suficientes con arreglar todos los errores que viene con cada actualización del juego (y futuros DLC).
5• Si piensas que esto va a ahorar tiempo por parte de ambas comunidades de traductores (al español castellano y latino), no cuentes con ello. No es para nada seguro, y como ya he mencionado, acabaría siendo trabajo innecesario. (Y sí hay diferencias significativas, por eso en America tienes que elegir qué dialécto quieres estudiar)

**Comment by LordMellington** [comment]
Estoy de acuerdo con Xeros. Hay razones para mantener separadas las versiones de traducción, debido no sólo a los modismos sino también a la diferencia a la hora de utilizar tiempos verbales, por ejemplo (en España usamos más variedad). Otra diferencia es el empleo de la forma de cortesía en todos o casi todos los países de América latina en situaciones que en España se consideran innecesarias.
Xeros y yo vamos a terminar con toda la traducción de RimWorld en aproximadamente una semana, de modo que cualquiera es libre de utilizarla para jugar, pero se llamará definitivamente "Español de España".
