### ISSUE TITLE
Error en etiqueta XML

### ISSUE THREAD

**Issue by Andres6936** [Ludeon/RimWorld-Spanish#49]
https://github.com/Ludeon/RimWorld-Spanish/blob/cd5a9de5d7dff2103aa31ad7f7855e5c7b05a98d/Royalty/DefInjected/FactionDef/Faction_Empire.xml#L10

La etiqueta debería de ser: 
```xml
<Empire.pawnSingular>Imperial</Empire.pawnSingular>
```
###### _(Nótese la 's' extra en la cadena original que ocasiona el problema)_

**Comment by Xeros08** [comment]
De hecho, eso ya está corregido, es solo que suelo subir los cambios cuando es necesario. No me gusta "spamear" el "botón" de "push".
