### ISSUE TITLE
Few typos

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-Spanish#64]
I noticed few typos here:
- Should be `<titleFemale>`
https://github.com/Ludeon/RimWorld-Spanish/blob/9e6e6ce9518de70599bc5d7026acc04f73500e21/Core/Backstories/Backstories.xml#L21
https://github.com/Ludeon/RimWorld-Spanish/blob/9e6e6ce9518de70599bc5d7026acc04f73500e21/Core/Backstories/Backstories.xml#L32

- Should be `<titleShortFemale>`
https://github.com/Ludeon/RimWorld-Spanish/blob/9e6e6ce9518de70599bc5d7026acc04f73500e21/Core/Backstories/Backstories.xml#L309
https://github.com/Ludeon/RimWorld-Spanish/blob/9e6e6ce9518de70599bc5d7026acc04f73500e21/Core/Backstories/Backstories.xml#L400

Best regards

**Comment by Xeros08** [comment]
Thanks, I have not had much free time recently, so thank you.

Gracias, no he tenido mucho tiempo libre últimamente, así que gracias.

**Comment by Zakees** [comment]
Solved! Thanks a lot :D
