### ISSUE TITLE
Qué falta por hacer

### ISSUE THREAD

**Issue by Xeros08** [Ludeon/RimWorld-Spanish#67]
Buenas, he decidido volver a traducir, y me gustaría saber qué traducciones faltan por hacer/revisar.

Pregunto porque según el `TranslationReport` no parece que falten traducciones por importar.
Tampoco parece que falten traducciones por hacer, ya que no encuentro ninguna etiqueta con `TODO` como contenido.

A excepción de un error en el archivo [RulePacks_Global.xml](https://github.com/Ludeon/RimWorld-Spanish/blob/master/Core/DefInjected/RulePackDef/RulePacks_Global.xml) (según el `TranslationReport`), no veo nada que hacer:

> Translated non-System.String field rulesFiles of type System.Collections.Generic.List`1[System.String] at path GlobalUtility.rulePack.rulesFiles. Expected System.String. (RulePacks_Global.xml)

He visto que @Zakees y @zerstrick han estado continuando con las traducciones desde que yo lo dejé, muchas gracias por vuestro trabajo. ^^

**Comment by zerstrick** [comment]
Hola @Xeros08 los TODO que estaban pendientes ya @Zakees los terminó, por ahora se está buscando errores, lo más grande que queda por hacer es adaptar los trasfondos, porque fueron importados de la versión latina y hay historias que todavía pueden tener algún error y otras que pueden mejorarse a como se habla en España.

**Comment by Zakees** [comment]
Además de lo que te comenta Zers, yo estoy personalmente revisando archivo a archivo, línea a línea, buscando errores ortográficos o redacciones que sean dificiles de comprender para rehacerlas de una forma más sencilla y que venga a ser lo mismo.

**Comment by Xeros08** [comment]
Perfecto, gracias.
Entonces me pondré a revisar los trasfondos.
Empezaré a revisar desde abajo hacia arriba.

**Comment by Zakees** [comment]
Si te parece bien, ponte con los backstories, que yo lo iba a dejar para el final, así no nos pisamos :D

**Comment by Xeros08** [comment]
> Si te parece bien, ponte con los backstories, que yo lo iba a dejar para el final, así no nos pisamos :D

Perfect

**Comment by Zakees** [comment]
Nos organizamos por Discord, cierro esto
