### ISSUE TITLE
Automatizar la "Instalación" de las traducciones?

### ISSUE THREAD

**Issue by Xeros08** [Ludeon/RimWorld-Spanish#68]
Lo he estado pensando, y creo que estaría bastante bien crear un Script para automatizar la instalación de las traducciones del Repositorio en el juego.

Creo que es una tarea relativamente fácil, y podría ahorrarnos bastante trabajo, además de servir para ayudar a que la gente descargue e instale las últimas traducciones directamente del repositorio. Sin tener que andar borrando y sustituyendo manualmente archivos. 

Para Windows habría que hacer un Batch file (.bat), y para Linux un Bash Script (.sh).
En caso de que os guste la idea, yo puedo hacerme cargo de ello, aunque tardaré un poco.
(Sobre todo porque hay gente que no tiene instalado el juego en la ruta por defecto, así que creo que hay que hacer bastante magia)

**Comment by zerstrick** [comment]
Ah eso es mucho mejor que mis métodos manuales xD (la gente e es floja) si se hace seguro muchos si actualizarán de forma constante ¿se podrá usar para la versión latina? es decir ¿podré adaptarlo?

**Comment by Xeros08** [comment]
> Ah eso es mucho mejor que mis métodos manuales xD (la gente e es floja) si se hace seguro muchos si actualizarán de forma constante ¿se podrá usar para la versión latina? es decir ¿podré adaptarlo?

Pues tenía pensado que el script fuese solo para esta traducción, porque si no se complica ya mucho la cosa.
Además, todavía estoy pensando en como hacerlo. Ya que hay varias formas.

**Comment by Xeros08** [comment]
Igualmente, los scripts solo son archivos de texto con una extensión específica. Así que siempre se puede editar y adaptar ^^
