### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by amatiasq** [Ludeon/RimWorld-Spanish#9]
There are some translations like this description that I can't find anywhere, not even on the spanish translation repo or in the program's english folder.

I looked for "pulling carts" and "learn" and found nothing. How can I provide proper translations?

---

Hay algunas traducciones como en la descripción de la foto que no puedo encontrar en ningún lado, ni en el repositorio de traducción a español ni en la carpeta de inglés del juego.

Busqué "pulling carts" y "learn" y no encontré nada. Como puedo proveer estas traducciones?

---
 
<img width="513" alt="captura de pantalla 2016-12-31 a las 14 53 29" src="https://cloud.githubusercontent.com/assets/1533589/21577819/f43eded2-cf68-11e6-83ed-b1da718d26a1.png">

**Comment by capiqua** [comment]
Me dijeron en el foro que es bug de todas las traducciones. Por lo que no se puede modificar con los archivos que nos dan hasta que algun ida lo corrigan

**Comment by mora145** [comment]
Estan en `RimWorld-Spanish/Backstories/Backstories.xml` Las estoy traduciendo, creo que para hoy mismo subo toda la traducción para luego corregirla.

**Comment by amatiasq** [comment]
Solucionado por @mora145
